api/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/', function () {
    return view('welcome');
});
*/

/*
 * Users
 * */
Route::resource('users', 'User\UserController', [
    'middleware' => 'auth'
]);

/*
 * Vehicles
 * */
Route::resource('vehicles', 'Vehicle\VehicleBackendController', [
    'middleware' => 'auth'
]);


/*
 * Customers
 * */
Route::resource('customers', 'Customer\CustomerBackendController', [
    'only' => ['index', 'show', 'edit', 'destroy'],
    'middleware' => 'auth'
]);


/*
 * Reservations
 * */
Route::resource('reservations', 'Reservation\ReservationBackendController', [
    'only' => ['index', 'show', 'destroy'],
    'middleware' => 'auth'
]);


/*
* Statistics
* */
Route::resource('home', 'Statistic\StatisticController', [
    'only' => ['index'],
    'middleware' => 'auth'
]);

Route::get('/', 'Statistic\StatisticController@index')->name('home');

/*
* Auth
* */
Auth::routes([
    'reset' => false
]);

/**
* Override the default auth register route to add middleware.
 */
Route::get('register', 'Auth\RegistrationController@showRegistrationForm')->name('register')->middleware('hasInvitation');
Route::get('register/request', 'Auth\RegistrationController@requestInvitation')->name('requestInvitation')->middleware('admin', 'auth');
Route::post('register', 'Auth\RegistrationController@register')->name('register');

/**
 * Invitations group with auth middleware.
 * Eventhough we only have one route currently, the route group is for future updates.
 */
Route::group([
    'middleware' => ['auth', 'admin'],
    'prefix' => 'invitations'
], function() {
    Route::get('', 'InvitationsController@index')->name('showInvitations');
});
/**
 * Route for storing the invitation. Only for guest users.
 */
Route::post('invitations', 'InvitationsController@store')->middleware('admin')->name('storeInvitation');

api/resources/views/pages/addVehicle.blade.php
    @extends('adminlte::page')

    @section('content')

    <div class="container">
        <div class="section">
    <h1 class="title">Import New Vehicle</h1>
    <form method="POST" action="{{ route('vehicles.store') }}" enctype="multipart/form-data">
    {{ csrf_field() }}

        {{-- <div class="form-group">
            <label for="make">Manufacturer</label>
            <select name="make" class="form-control">
                <option disabled selected value style="display: none;"> </option>
                @foreach($makes as $key => $value)
                    <option value="{{ $key }}">{{ $value['name'] }}</option>
                    @endforeach
            </select>
        </div>

        @if ($errors->has('make'))
        <div>
        {{ $errors->first('make') }}
        </div>
        @endif --}}

        <div class="form-group">
            <label for="model_id">Model</label>
            <select name="model_id" class="form-control">
                <option disabled selected value style="display: none;">  </option>
                @foreach($models as $model)
                    <option value="{{ $model['id'] }}"> {{ $model->makeOfVehicle['name'] }} {{ $model['name'] }}</option>
            @endforeach
            </select>
        </div>
        
        <div class="form-group">
            <label for="type">Type</label>
            <select name="type" class="form-control">
                <option disabled selected value style="display: none;"></option>
                <option value="hatchback">Hatchback</option>
                <option value="electric">Electric</option>
                <option value="supercar">Supercar</option>
                <option value="limousine">Limousine</option>
                <option value="sport">Sport</option>
                <option value="suv">SUV</option>
                <option value="caravan">Caravan</option>
            </select>
        </div>

        <div class="form-group">
            <label for="door_number">Door Number</label>
            <select name="door_number" class="form-control">
                <option disabled selected value style="display: none;"></option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
            </select>
            {{-- <input type="text" name="door_number" class="form-control {{ $errors->has('door_number') ? 'is-danger' : '' }}" placeholder="@if ($errors->has('door_number')) {{ $errors->first('door_number') }} @else   @endif"> --}}
        </div>

        <div class="form-group">
            <label for="gearbox">Gearbox</label>
            <select name="gearbox" class="form-control">
                <option disabled selected value style="display: none;"></option>
                <option value="automatic">Automatic</option>
                <option value="manual">Manual</option>
            </select>
            {{-- <input type="checkbox" name="gearbox" value="1" class="form-check-input"> --}}
        </div>


        <div class="form-group">
        <label for="auto_ac"> AC </label>
        <select name="auto_ac" class="form-control">
            <option disabled selected value style="display: none;"></option>
            <option value="true">Yes</option>
            <option value="false">No</option>
        </select>
        {{-- <input type="checkbox" name="auto_ac" value='1' class="form-check-input"> --}}
        </div>

        <div class="form-group">
            <label for="engine_power">Engine Power <small>(kW)</small> </label>
            <input type="number" name="engine_power" class="form-control {{ $errors->has('engine_power') ? 'is-danger' : '' }}" placeholder="@if ($errors->has('engine_power')) {{ $errors->first('engine_power') }} @else   @endif">
        </div>

        <div class="form-group">
            <label for="price">Price <small>(HRK)</small> </label>
            <input type="number" name="price" class="form-control">
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control {{ $errors->has('description') ? 'is-danger' : '' }}" name="description" placeholder="@if ($errors->has('description')) {{ $errors->first('description') }} @else  @endif"></textarea>
        </div>

        <div class="form-group">
            <label for="filename">Photo(s)</label>
            <input type="file" name="filename[]" multiple class="form-control-file">
        </div>

        {{-- <div class="input-group control-group increment" >
                <input type="file" name="filename[]" class="form-control">
                <div class="input-group-btn"> 
                  <button class="btn btn-success" type="button"><i class="glyphicon glyphicon-plus"></i>Add</button>
                </div>
              </div>
              <div class="clone hide">
                    <div class="control-group input-group" style="margin-top:10px">
                      <input type="file" name="filename[]"  class="form-control">
                      <div class="input-group-btn"> 
                        <button class="btn btn-danger" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                      </div>
                    </div>
                  </div> --}}

        <div>
            <button type="submit" class="btn btn-primary" style="margin-top: 1rem;">Submit</button>
        </div>

    </form>
</div>
    </div>

    <script type="text/javascript"> 
        $(document).ready(function() {
    
          $(".btn-success").click(function(){ 
              var html = $(".clone").html();
              $(".increment").after(html);
          });
    
          $("body").on("click",".btn-danger",function(){ 
              $(this).parents(".control-group").remove();
          });
    
        });
    </script>

    @endsection

api/resources/views/pages/customer.blade.php
@extends('adminlte::page')

@section('content')
<div class="container">

        <figure class="figure" style="background: #f0f0f0; padding: 20px; text-align: center; width:400px; margin:20px auto; border-radius:15px; box-shadow: 1px 1px 5px 2px #333;">
                <h1 class="title" style="margin-top:0;">Customer ID: {{ $customer->id }}</h1>
                <figcaption class="figure-caption">
                        <ul style="list-style: none; font-size: 2rem; text-align:left;">
                                <li><span style="font-weight:bold;">Username:</span> {{ $customer->username }}</li>
                                <li><span style="font-weight:bold;">Name:</span> {{ $customer->name }}</li>
                                <li><span style="font-weight:bold;">Last Name:</span> {{ $customer->lastname }}</li>
                                <li><span style="font-weight:bold;">Email:</span> {{ $customer->email }}</li>
                                <li><span style="font-weight:bold;">Is Verified:</span> @if ( $customer->verified ) verified @else not verified @endif</li>
                        </ul>
                </figcaption>
            <form method="POST" action="/customers/{{ $customer->id }}" style="margin-top: 1rem">
                @method('DELETE')
                @csrf
                
                <div class="field">
                        <div class="control">
                            <button type="submit" class="btn btn-danger" style="width: 100px;">Delete</button>
                        </div>
                    </div>
            </form>
            </figure>

</div>


@endsection

api/resources/views/pages/customers.blade.php
@extends('adminlte::page')

@section('content')
    <h1 class="title" style="margin-top: 0;">Customers</h1>
<hr>

    <table id="table1" class="display cell-border table table-striped table-bordered" style="font-size: 2rem; background-color: #fff;  border: 2px solid #ccc;">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th style="text-align:right;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($customers as $customer)
                <tr>
                    <td>{{ $customer->username }}</td>
                    <td>{{ $customer->name }}</td>
                    <td>{{ $customer->lastname }}</td>
                    <td>{{ $customer->email }}</td>
                    <td style="text-align:right;">
                        {{-- <button class="btn btn-primary" data-customerid={{$customer->id}} data-toggle="modal" data-target="#about"><span class="glyphicon glyphicon-eye-open"></span> About</button> --}}

                      <a href="customers/{{ $customer->id }}">
                        <button class="btn btn-primary"><span class="glyphicon glyphicon-eye-open"></span> About</button>
                      </a>

                    {{-- { <button class="btn btn-danger" data-customerid={{$customer->id}} data-toggle="modal" data-target="#delete"><span class="glyphicon glyphicon-trash"></span> Delete</button> --}} 
                     <form method="POST" action="/customers/{{ $customer->id }}" style="display:inline;">
                      @method('DELETE')
                      @csrf
                         <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</button>
                  </form>   
                  </td>
                </tr>
                {{-- <a href="{{ url('customers/'. $customer->id) }}"></a> --}} <!-- LINK ZA JEDNOG CUSTOMERA -->
                @endforeach
            </tbody>
          </table>

         

          

@endsection

api/resources/views/pages/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit')

@section('content')

<?php  
    $doors = [2,3,4,5];
    $types = ['Hatchback', 'Sedan', 'SUV', 'Sport', 'Wagon', 'Coupe', 'Compact', 'Crossover', 'Van'];
    $gears = ['Automatic', 'Manual'];
    $ACs = ['Yes', 'No'];
?>
<div class="container">
    <div class="section">


    {{-- {{ Form::model($vehicle, array('route' => array('vehicles.edit', $vehicle->id))) }} --}}


    <form method="POST" action="/vehicles/{{ $vehicle->id }}" style="margin-bottom: 1rem">
        {{ method_field('PATCH') }}
        {{ csrf_field() }}

        {{-- <div class="form-group">
            <label for="make" class="">Manufacturer</label>

            <div class="control">
                <input type="text" class="form-control" name="make" placeholder="{{ $vehicle->make }}">
            </div>
        </div> --}}

        <div class="form-group">
                <label for="model_id">Model</label>
                <select name="model_id" class="form-control">
                    <option value="0">--Select--</option>
                    @foreach($models as $model)
                        <option value="{{ $model['id'] }}" {{$vehicle->model_id == $model['id'] ? 'selected="selected"' : '' }}> {{ $model->makeOfVehicle['name'] }} {{ $model['name'] }}</option>
                @endforeach
                </select>
            </div>
            
            <div class="form-group">
                <label for="type">Type</label>
                <select name="type" class="form-control">
                    <option value="0">--Select--</option>
                    @foreach($types as $type)
                        <option value="{{ $type }}" {{$vehicle->type == $type ? 'selected="selected"' : '' }}> {{ $type }}</option>
                @endforeach
                </select>
            </div>
    
            <div class="form-group">
                <label for="door_number">Door Number</label>
                <select name="door_number" class="form-control">
                    <option value="0">--Select--</option>
                    @foreach($doors as $door)
                    <option value="{{ $door }}" {{$vehicle->door_number == $door ? 'selected="selected"' : '' }}>{{ $door }}</option>   
                    @endforeach
                </select>
                {{-- <input type="text" name="door_number" class="form-control {{ $errors->has('door_number') ? 'is-danger' : '' }}" placeholder="@if ($errors->has('door_number')) {{ $errors->first('door_number') }} @else   @endif"> --}}
            </div>
    
            <div class="form-group">
                <label for="gearbox">Gearbox</label>
                <select name="gearbox" class="form-control">
                    <option value="0">--Select--</option>
                    @foreach($gears as $gearbox)
                    <option value="{{ $gearbox }}" {{$vehicle->gearbox == $gearbox ? 'selected="selected"' : '' }}>{{ $gearbox }}</option>
                    @endforeach
                </select>
                {{-- <input type="checkbox" name="gearbox" value="1" class="form-check-input"> --}}
            </div>
    
    
            <div class="form-group">
            <label for="auto_ac"> AC </label>
            <select name="auto_ac" class="form-control">
            <option value="0">--Select--</option>
            @foreach($ACs as $ac)
            <option value="{{ $ac }}" {{ $vehicle->auto_ac == $ac ? 'selected="selected"' : '' }}>{{ $ac }}</option>
            @endforeach
            
            </select>
            {{-- <input type="checkbox" name="auto_ac" value='1' class="form-check-input"> --}}
            </div>
    
            <div class="form-group">
                <label for="engine_power">Engine Power <small>(kW)</small> </label>
            <input type="text" name="engine_power" class="form-control {{ $errors->has('engine_power') ? 'is-danger' : '' }}" placeholder="@if ($errors->has('engine_power')) {{ $errors->first('engine_power') }} @else   @endif" value="{{ $vehicle->engine_power }}">
            </div>
    
            <div class="form-group">
                <label for="price">Price <small>(HRK)</small> </label>
                <input type="number" name="price" class="form-control" value="{{ $vehicle->price }}">
            </div>
    
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control {{ $errors->has('description') ? 'is-danger' : '' }}" name="description" placeholder="@if ($errors->has('description')) {{ $errors->first('description') }} @else  @endif" value="{{ $vehicle->description }}"></textarea>
            </div>
    
            {{-- <div class="form-group">
                <label for="filename">Photo(s)</label>
                <input type="file" name="filename[]" multiple class="form-control-file">
            </div> --}}


        <div class="form-group">
            <div class="control">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>

    </form>
    

</div>
</div>
@endsection

api/resources/views/pages/editCustomer.blade.php
@extends('adminlte::page')

@section('title', 'Edit')

@section('content')
<div class="container">
    <div class="section">

  
    <h1 class="title">Edit Customer</h1>
    <h2 class="subtitle">ID: {{ $customer->id }}</h2>


    <form method="POST" action="/customers/{{ $customer->id }}" style="margin-bottom: 1rem">
        {{ method_field('PATCH') }}
        {{ csrf_field() }}

        <div class="form-group">
            <label for="name" class="">Name</label>

            <div class="control">
                <input type="text" class="form-control" name="name" placeholder="{{ $customer->name }}">
            </div>
        </div>

        <div class="form-group">
            <label for="lastname" class="">Last Name</label>

            <div class="control">
                <input type="text" class="form-control" name="lastname" placeholder="{{ $customer->lastname }}">
            </div>
        </div>

        <div class="form-group">
            <label for="email" class="">Email</label>

            <div class="control">
                <input type="text" class="form-control" name="email" placeholder="{{ $customer->email }}">
            </div>
        </div>

        <div class="form-group">
            <div class="control">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>

    </form>
    

</div>
</div>
@endsection

api/resources/views/pages/reservation.blade.php
@extends('adminlte::page')

@section('content')
<div class="container">
        <h1 class="title" style="margin-top:0; text-align:center; padding:10px;  color:#333;">Reservation ID: {{ $reservation->id }} </h1>
       
        <figure class="figure" style="background: #f0f0f0; padding: 20px; text-align: center; width:400px; margin:20px auto; border-radius:15px; box-shadow: 1px 1px 5px 2px #333;">
                <h1 style="margin-top:0; text-align:center;">Customer ID: {{ $reservation->customer['id'] }}</h1>
                <figcaption class="figure-caption">
                        <ul style="list-style: none; font-size: 2rem; text-align:left;">
                                <li><span style="font-weight:bold;">Username:</span> {{ $reservation->customer['username'] }}</li>
                                <li><span style="font-weight:bold;">Name:</span> {{ $reservation->customer['name'] }}</li>
                                <li><span style="font-weight:bold;">Last Name:</span> {{ $reservation->customer['lastname'] }}</li>
                                <li><span style="font-weight:bold;">Email:</span> {{ $reservation->customer['email'] }}</li>
                        </ul>
                </figcaption>
               
            
            </figure>


            <figure class="figure" style="background: #f0f0f0; padding: 20px; text-align: center; width:400px; margin:20px auto;  border-radius:15px; box-shadow: 1px 1px 5px 2px #333;">
                    <h1 class="title" style="margin-top:0;">reservation ID: {{ $reservation->vehicle['id'] }}</h1>
                    {{-- <img src="{{ asset($reservation->vehicle['image']) }}" class="figure-img img-fluid rounded" style="border: 2px solid #333; border-radius:10px; width:285px;"> --}}
                    @foreach ($reservation->vehicle->images as $image)
        <?php $i = $i+1 ?> 
        <img class="figure-img img-fluid rounded" src="{{ asset($image->filename) }}" alt="" style="border: 2px solid #333; border-radius:10px; width:285px;">
        @if ($i > 1) @break @endif
    @endforeach
                    <figcaption class="figure-caption">
                            <ul style="list-style: none; font-size: 2rem; text-align:left;">
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Make:</span> {{ $reservation->vehicle->modelOfVehicle->makeOfVehicle['name'] }}</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Model:</span> {{ $reservation->vehicle->modelOfVehicle['name'] }}</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Type:</span> {{ $reservation->vehicle['type'] }}</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Power:</span> {{ $reservation->vehicle['engine_power'] }} kW</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Doors:</span> {{ $reservation->vehicle['door_number'] }}</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Gearbox:</span> {{ $reservation->vehicle['gearbox'] }}</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">AC:</span> {{ $reservation->vehicle['auto_ac'] }}</li>
                            <li style=" border-bottom:1px solid #999;"><span style="font-weight:bold;">Price:</span> {{ $reservation->vehicle['price'] }} HRK</li>
                            <li><span style="font-weight:bold;">Status:</span> {{ $reservation->vehicle['status'] }}</li>
                            </ul>
                    </figcaption>
                  
                </figure>
                
                
<form method="POST" action="/reservations/{{ $reservation->id }}" style="margin-top: 2rem; text-align:center;">
    @method('DELETE')
    @csrf
    
    <div class="field">
            <div class="control">
                <button type="submit" class="btn btn-danger" style="width: 200px;">Delete</button>
            </div>
        </div>
</form>
</div>

@endsection

api/resources/views/pages/reservations.blade.php
@extends('adminlte::page')

@section('content')
<h1 class="title" style="margin-top:0;">Reservations</h1>
<hr>

 <table id="table1" class="display cell-border table table-striped table-bordered" style="font-size: 2rem; background-color: #fff;  border: 2px solid #ccc;">
  <thead>
      <tr>
          <th>Customer</th>
          <th>Vehicle</th>
          <th style="text-align:right;">Actions</th>
      </tr>
  </thead>
  <tbody>
      @foreach($reservations as $reservation)
      <tr>
      <td>{{ $reservation->customer['name'] }} {{ $reservation->customer['lastname'] }}</td>
          <td>{{ $reservation->vehicle->modelOfVehicle->makeOfVehicle['name'] }} {{ $reservation->vehicle->modelOfVehicle['name'] }}</td>
          <td style="text-align:right;">
            {{-- <button class="btn btn-primary" data-reservationid={{$reservation->id}} data-toggle="modal" data-target="#about"><span class="glyphicon glyphicon-eye-open"></span> About</button> --}}
            <a href="reservations/{{ $reservation->id }}">
              <button class="btn btn-primary"><span class="glyphicon glyphicon-eye-open"></span> About</button>
            </a>
            {{-- <button class="btn btn-danger" data-reservationid={{$reservation->id}} data-toggle="modal" data-target="#delete"><span class="glyphicon glyphicon-trash"></span> Delete</button> --}}
            <form method="POST" action="/reservations/{{ $reservation->id }}" style="display:inline;">
              @method('DELETE')
              @csrf
                 <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</button>
          </form>
        </td>
      </tr>
      {{-- <a href="{{ url('reservations/' .$reservation->id) }}"></a> --}} <!-- LINK ZA JEDNO VOZILO -->
      @endforeach
  </tbody>
</table>



@endsection

api/resources/views/pages/statistic.blade.php
@extends('adminlte::page')

@section('content')
{{-- <div class="content-header" style="font-size:2rem;"> --}}
       <h1 class="title" style="margin-top:0;">Dashboard</h1>
       <hr>
{{-- </div> --}}

<div class="row" style="margin: 10px; font-size: 2rem;">
        
              
          <!-- small box -->
          <div class="small-box bg-green">
                <div class="inner">
                  <h3>{{ $vehicles->count() }}</h3>
    
                  <h1>Vehicles</h1>
                </div>
                <div class="icon">
                  <i class="ion ion-android-car"></i>
                </div>
                <a href="vehicles" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
        
              
          <!-- small box -->
          <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>{{ $customers->count() }}</h3>
    
                  <h1>Customers</h1>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="customers" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>

                
               <!-- small box -->
          <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>{{ $reservations->count() }}</h3>
    
                  <h1>Reservations</h1>
                </div>
                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
                <a href="reservations" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            
</div>
@endsection

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@endsection

api/resources/views/pages/user.blade.php
@extends('adminlte::page')

@section('content')
<div class="container">

        <figure class="figure" style="background: #f0f0f0; padding: 20px; text-align: center; width:400px; margin:20px auto; border-radius:15px; box-shadow: 1px 1px 5px 2px #333;">
                <h1 class="title" style="margin-top:0;">Admin ID: {{ $user->id }}</h1>
                <figcaption class="figure-caption">
                        <ul style="list-style: none; font-size: 2rem; text-align:left;">
                                <li><span style="font-weight:bold;">Name:</span> {{ $user->name }}</li>
                                <li><span style="font-weight:bold;">Email:</span> {{ $user->email }}</li>
                                {{-- <li><span style="font-weight:bold;">Is Verified:</span> @if ( $user->admin ) verified @else not verified @endif</li> --}}
                        </ul>
                </figcaption>
            </figure>

</div>


@endsection

api/resources/views/pages/users.blade.php
@extends('adminlte::page')

@section('content')
    <h1 class="title" style="margin-top:0;">Users</h1>
    <hr>


    <table id="table1" class="display cell-border table table-striped table-bordered" style="font-size: 2rem; background-color: #fff;  border: 2px solid #ccc;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td style="text-align:right;">
                        <a href="users/{{ $user->id }}">
                        <button class="btn btn-primary" data-userid={{$user->id}} data-toggle="modal" data-target="#about"><span class="glyphicon glyphicon-eye-open"></span> About</button>
                      </a>
                      </td>
                </tr>
                {{-- <a href="{{ url('users/'. $user->id) }}"></a> --}} <!-- LINK ZA JEDNOG userA -->
                @endforeach
            </tbody>
          </table>

       


@endsection